ingress:
  name: ingress-service
  replicaCount: 1
  annotations:
    # class: nginx
    class: k8s.io/ingress-nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          backend:
            service:
              name: serviceName
              port:
                number: 8080
